In [2]:
import numpy as np
arr = [1,2,3,445,5]
arr

[1, 2, 3, 445, 5]

In [11]:
n = np.array(3,dtype=int)
print(n)

TypeError: argument for array() given by name ('dtype') and position (position 1)

In [16]:
x = [1,2,3,4,'5']
b = np.array(x,dtype = int)
b
print(b)
print(b[0])
print(x[0])
print(b[0]+b[1])

[1 2 3 4 5]
1
1
3


In [18]:
a = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(a,dtype = int)
a
print(a[1][1])

5


In [28]:
s = np.ones(9,dtype =int)
s
x = np.zeros(1,dtype=int)
print(x)
c=[]
c = s + x
print(c)


[0]
[1 1 1 1 1 1 1 1 1]


In [32]:
np.empty([4,4],dype=int)


TypeError: empty() got an unexpected keyword argument 'dype'

In [38]:
a = [1,2,3,4,5]
b = np.array(a)
print(a[1])
print(b[1])
#slicing
print(a[1:])
print(b[1:])

2
2
[2, 3, 4, 5]
[2 3 4 5]


In [4]:
import numpy as np
arr = [[1,2,3],[4,5,6],[7,8,9]]
x = np.array(arr)
print(x)
print(x[0:2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6]
