In [1]:
import numpy as np
a = [1,2,3,0,0,3]
b = np.array(a)
print(b)

[1 2 3 0 0 3]


In [8]:
s = (b!=0)
new_b = b[s]
new_b

array([1, 2, 3, 3])

In [9]:
a

[1, 2, 3, 0, 0, 3]

In [24]:
s= [3,3,3,3,3,3]
b1 = np.array(s)
# print(a)
print(b)
mul_x = (a%b1==0)

new_a = b[mul_x]
new_a

[3, 3, 3, 3, 3, 3]


TypeError: only integer scalar arrays can be converted to a scalar index

In [33]:
o = [1,2,3,4,5,6,7,8,9,10]
fo = np.array(o)
od = [2]
fod = np.array(od)
x = (fo%fod!=0)
fo[x]=-1
fo


array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])