In [6]:
import numpy as np


l = [1,2,4,5,6,43,1]
x = np.array(l)
x = x+1
x

array([ 2,  3,  5,  6,  7, 44,  2])

In [17]:
x

array([1, 2, 3, 4, 5])

In [19]:
x == 1

array([ True, False, False, False, False])

In [14]:
import numpy as np
a = [1,2,3,4,5]
x = np.array(a)
l=x.sum()
l

15

In [15]:
print(x.mean())

3.0


In [20]:
arr = [1,2,0,0,6]
l = np.array(arr)
l

array([1, 2, 0, 0, 6])

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()